"""Constant numbers used in remove-background."""

# Seed for random number generators.
RANDOM_STATE = 1234

# Constants across all modes
DEFAULT_TOTAL_COUNTS_NMADS = 5
DEFAULT_N_FEATURES_NMADS = 5
DEFAULT_PCT_COUNTS_IN_TOP_FEATURES_NMADS = 5

# Constants for RNA mode
DEFAULT_N_FEATURES_LOW = 500  # Also used in ATAC mode
DEFAULT_N_FEATURES_HI = 7000
DEFAULT_PCT_COUNTS_MT_NMADS = 3
DEFAULT_PCT_COUNTS_MT_HI = 8

# Constants for ATAC mode
DEFAULT_TOTAL_COUNTS_LOW = 10000
DEFAULT_TOTAL_COUNTS_HI = 65000
DEFAULT_NS_NMADS = 3
DEFAULT_NS_HI = 2
DEFAULT_TSS_NMADS = 3
DEFAULT_TSS_LOW = 1
DEFAULT_TSS_HI = 3

# Others
DEFAULT_MIN_CELLS_PER_FEATURE = None
DEFAULT_MAX_CELL_COUNT_FOR_PRELIM_FILTER = 100000
DEFAULT_N_FOR_NS_CALC = 1e3
DEFAULT_N_TSS = 1000
