"""Constant numbers used in remove-background."""

# Seed for random number generators.
RANDOM_SEED = 1234

# Constants for qc script
DEFAULT_TOTAL_COUNTS_NMADS = 5
DEFAULT_N_FEATURES_BY_COUNTS_NMADS = 5
DEFAULT_PCT_COUNTS_IN_TOP_FEATURES_NMADS = 5
DEFAULT_PCT_COUNTS_MT_NMADS = 3
DEFAULT_PCT_COUNTS_MT_THRESHOLD = 8
DEFAULT_N_FEATURES_LOW_THRESHOLD = 500
DEFAULT_N_FEATURES_HIGH_THRESHOLD = 7000
DEFAULT_MIN_CELLS = None

#
DEFAULT_MAX_CELL_COUNT = 100000
