"""Constant numbers used in reduce-dimensions."""

import numpy as np


DEFAULT_NUM_HVGS = 3000
DEFAULT_N_NEIGHBORS = 30
DEFAULT_N_COMPONENTS = 50
DEFAULT_CLUST_RESOLUTION = 1
DEFAULT_UMAP_MIN_DISTANCE = 0.3
RANDOM_STATE = 1234
