"""Constant numbers used in reduce-dimensions."""

import numpy as np


DEFAULT_INITIAL_NUM_HVGS = 3000
DEFAULT_INITIAL_N_NEIGHBORS = 30
DEFAULT_INITIAL_N_COMPONENTS = 50
DEFAULT_INITIAL_CLUST_RESOLUTION = 1
DEFAULT_UMAP_MIN_DISTANCE = 0.3
RANDOM_STATE = 1234
